### ISSUE TITLE
Remove app until district approves

### ISSUE THREAD

**Issue by mickey167** [FaceyComputers/BFH-Android-New#4]
I had to remove the app from the app store until it could be approved by the district.

They are worried about boxclevers copyright.  I do not believe it will be a problem, but we need to wait and see.

**Comment by supamonkey2000** [comment]
@mickey167 Sorry I did not see this issue until just now. I thought it was a bug in Google Play so I put it back up. I'll keep it removed until central or boxclever approves.

Is hosting the APK's on Github ok?

**Comment by mickey167** [comment]
I don't know.  Could you remove them for now?

I don't think there is any issues with it, but central is worried it might violate the contract with b0xcl3v3r, so they want to check the contract before it is publicly available.

**Comment by supamonkey2000** [comment]
Removed APKs from Github
