### ISSUE TITLE
The App is broken

### ISSUE THREAD

**Issue by mickey167** [FaceyComputers/BFH-Android-New#6]
## Category 
UI, Copyright, Backend, Media, Networking, Installation, Compatibility, Other

## Severity
, Extreme

## What happpened?
App failed to load

**Comment by tycrek** [comment]
I'm at work right now on my break, I'll get right on that after work. I have a feeling it has to do with the website layout changing.

Also, are eteacher pages still a thing? I can't seem to find them on the website but google search still works.

**Comment by mickey167** [comment]
I didn't mean for you to rush to fix it.  I was showing my grade 11s how to file tickets on GitHub and used this as an example.
If you could fix it that would be great.  I was going to try to figure the app out over November break.

**Comment by tycrek** [comment]
App has been fixed and manifests have been updated for Android SDK changes. New app version is `v2.0.0` and using build `b49`. Just waiting on Kim to provide me with login creds for Play Console.
